
# Supported architectures are i686, x86_64 and arm.
ARCH_LIST="i686 x86_64 arm"


SITE=https://landley.net/bin/toolchains/latest # https://musl.cc no longer downloads to Github - tar.xz instead tgz

X86_CC=i686-linux-musl-cross.tar.xz
X86_64_CC=x86_64-linux-musl-cross.tar.xz
ARM_CC=armv7l-linux-musleabihf-cross.tar.xz #armv7 does not support original Pi zero but does support zero 2


#SITE=https://musl.cc

#X86_CC=i686-linux-musl-cross.tgz
#X86_64_CC=x86_64-linux-musl-cross.tgz
#ARM_CC=armv6-linux-musleabihf-cross.tgz #armv6 still supports original Pi zero

