permissions: write-all
name: release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./build.sh
          gh release create $(date '+%F') -t $(date '+%F') --generate-notes *.tar.xz

